### ISSUE TITLE
Update alexa-remote/releases/tag/v3.7.1

### ISSUE THREAD

**Issue by cakebake** [cakebake/node-red-contrib-alexa-remote-cakebaked#1]
Request: https://github.com/586837r/node-red-contrib-alexa-remote2/issues/191

**Comment by cakebake** [comment]
Updated https://flows.nodered.org/node/node-red-contrib-alexa-cakebaked to v4.0.1

**Comment by cakebake** [comment]
Seems OK for me ... closing.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/7462226/107083479-f9c4ba00-67f5-11eb-91d8-309f7c07b6d0.png">

**Comment by SvenXP** [comment]
Thanks for the update!!!

I have one question, cause i wanted yesterday to try myself to update: where do you get the npmjs links and the hash codes?

"resolved": "https://registry.npmjs.org/alexa-remote2/-/alexa-remote2-3.7.1.tgz",
			"integrity": "sha512-68OkIGD8a5iO1mm0S5w6Tg5vTuKeUf2xwpFvJTEGGUvzhmknE9di7P4/A2flDl0zymNlt5/Os5Sl2RbEhtchOw==",

Couldnt find it anywhere :-(

**Comment by cakebake** [comment]
> I have one question, cause i wanted yesterday to try myself to update: where do you get the npmjs links and the hash codes?

Unfortunately I don't know exactly what you mean. NPM does this automatically - that's the job of a package manager. The check sums you address are automatically logged. 

The easiest way to update is via the UI in Node-Red.
