### ISSUE TITLE
the listening node is not working!

### ISSUE THREAD

**Issue by hassiomanuel90** [cakebake/node-red-contrib-alexa-remote-cakebaked#12]
Listening node (alexa event - device activity) does not work with cakebaked. The node does not return any voice payloads. It worked with alexaremote2. It was very useful! Will it be restored? Thank you

**Comment by flashbacck** [comment]
I had mine start failing several days ago. I'm not sure if my issue is the same as yours... I had a custom voice trigger that checked for msg.payload.activityStatus = SUCCESS and then msg.payload.description.summary for my trigger word. Alexa started responding "I don't have a device named doors blahblah." In payload.activitystatus it was returning "FAULT." So what I did was create a custom routine in the Alexa app that recognized the command "Alexa, check the doors" and the action is Wait 5 Seconds. It now recognizes the command, so activitystatus is SUCCESS, and the wait just causes a chime to play. The trigger part of my flow is below. Hope that helps.

`[{"id":"72cb396c.2758e8","type":"group","z":"7d3d0560.4703fc","name":"Alexa Device Specific Queries","style":{"label":true,"color":"#001f60","fill":"#addb7b"},"nodes":["447bda97.d746a4","d2d2ddc8.f1781","b0815c4c.9f9f8","28c33e85.32afe2"],"x":34,"y":439,"w":742,"h":142},{"id":"447bda97.d746a4","type":"alexa-remote-event","z":"7d3d0560.4703fc","g":"72cb396c.2758e8","name":"","account":"","event":"ws-device-activity","x":150,"y":520,"wires":[["d2d2ddc8.f1781"]]},{"id":"d2d2ddc8.f1781","type":"switch","z":"7d3d0560.4703fc","g":"72cb396c.2758e8","name":"AlexaVoiceMessageCheck","property":"payload.activityStatus","propertyType":"msg","rules":[{"t":"eq","v":"SUCCESS","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":420,"y":480,"wires":[["b0815c4c.9f9f8"]]},{"id":"b0815c4c.9f9f8","type":"switch","z":"7d3d0560.4703fc","g":"72cb396c.2758e8","name":"Filter Commands","property":"payload.description.summary","propertyType":"msg","rules":[{"t":"eq","v":"alexa check the doors","vt":"str"}],"checkall":"false","repair":false,"outputs":1,"x":400,"y":540,"wires":[["28c33e85.32afe2"]]},{"id":"28c33e85.32afe2","type":"switch","z":"7d3d0560.4703fc","g":"72cb396c.2758e8","name":"pass message","property":"payload","propertyType":"msg","rules":[{"t":"nnull"}],"checkall":"true","repair":false,"outputs":1,"x":670,"y":540,"wires":[[]]}]`

**Comment by hassiomanuel90** [comment]
thank you!
