### ISSUE TITLE
smarthome entity not found

### ISSUE THREAD

**Issue by tdejneka** [cakebake/node-red-contrib-alexa-remote-cakebaked#4]
Just switched from the now non-functional node-red-contrib-alexa-remote2 to node-red-contrib-alexa-remote-cakebaked. My existing flow (which used to work with remote2 prior to the recent failure) reports:

> smarthome entity not found

Node-red debug screenshot:
![Screenshot from 2021-02-23 15-11-06](https://user-images.githubusercontent.com/44732909/108901958-81c60480-75e9-11eb-81a4-b592628bd4ae.png)

The SmartHome Action node receives the correct commands (first message in the screenshot) but the response to the request is a failure to find the entity.

`Living Room Light` is one of several devices that has been discovered and registered by Alexa:
![Screenshot from 2021-02-23 15-19-47](https://user-images.githubusercontent.com/44732909/108903040-d918a480-75ea-11eb-9062-66a25ff340f8.png)

Let me know what additional information may be required to debug this issue.

**Comment by tdejneka** [comment]
Here's more information.

I tried this simple flow:

![Screenshot from 2021-02-23 15-41-53](https://user-images.githubusercontent.com/44732909/108905627-ef742f80-75ed-11eb-8401-b38bf7f63d85.png)

Where Smarthome Turn On is configured like this:

![Screenshot from 2021-02-23 15-40-44](https://user-images.githubusercontent.com/44732909/108905688-0286ff80-75ee-11eb-946a-57afa11f1955.png)

The result is "unexpected response layout":

![Screenshot from 2021-02-23 15-42-31](https://user-images.githubusercontent.com/44732909/108905734-0fa3ee80-75ee-11eb-9148-ce86d88eebcd.png)

**Comment by tdejneka** [comment]
I just examined the node-red/node_modules directory and can confirm it does _not_ contain node-red-contrib-alexa-remote2 which I had removed via the UI (after deleting all instances of its nodes from my flow).

The directory contains a node-red-contrib-alexa-remote-cakebaked sub-directory but I noticed it also contains an alexa-remote2 sub-directory. Is that correct or is it a leftover that is possibly interfering with the cakebaked version?

**Comment by MattL0** [comment]
Here i use the other fork( cliked on this one first). The directory alexa-remote-2 is outside the alexa-remotecontrib[..]fork directory (directly in nodered nodes_module directory)

**Comment by tdejneka** [comment]
> The directory alexa-remote-2 is outside the alexa-remotecontrib[..]fork directory 

Yes, that's what I mentioned in my previous post. What I see is this:
```
/usr/share/hassio/homeassistant/node-red/node_modules/alexa-remote2
/usr/share/hassio/homeassistant/node-red/node_modules/node-red-contrib-alexa-cakebaked
```
The contents of `alexa-remote2`
```
drwxr-xr-x   4 root root  4096 Feb 22 12:36 .
drwxr-xr-x 153 root root  4096 Feb 22 12:36 ..
-rwxr-xr-x   1 root root 96676 Oct 26  1985 alexa-remote.js
-rwxr-xr-x   1 root root 22564 Oct 26  1985 alexa-wsmqtt.js
drwxr-xr-x   2 root root  4096 Feb 22 12:36 example
-rw-r--r--   1 root root  1150 Oct 26  1985 LICENSE
drwxr-xr-x   3 root root  4096 Feb 22 12:36 node_modules
-rw-r--r--   1 root root  2003 Feb 22 12:36 package.json
-rw-r--r--   1 root root 11007 Oct 26  1985 README.md
```
My question is the `alexa-remote2` directory a _leftover_ from `node-red-contrib-alexa-remote2` or is it employed by `node-red-contrib-alexa-remote-cakebaked`?

If it's a leftover then does it potentially interfere with `node-red-contrib-alexa-remote-cakebaked`?

**Comment by tdejneka** [comment]
I uninstalled `node-red-contrib-alexa-remote-cakebaked` (via the UI), restarted node-red and noticed the `alexa-remote2` and `alexa-cookie2` directories disappeared so they're related.

I re-installed `node-red-contrib-alexa-remote-cakebaked` and noticed the related directories were present again.

I reconfigured `node-red-contrib-alexa-remote-cakebaked` again but it still fails to work:

![Screenshot from 2021-02-24 17-22-28](https://user-images.githubusercontent.com/44732909/109073930-0d609380-76c5-11eb-942f-98d0b0c89fca.png)

Any guidance to resolve this would be appreciated.

**Comment by bwims** [comment]
This is not a true fork, as I understand it.  Cakebaked has generously taken the code and made necessary changes so that after installation everything was as before, with updates.

My guess is this is a regional problem.   I suspect Amazon are rolling out changes on a staggered basis and don't care about non-monetised developers making something useful.

Which country are you logging in to?  If not UK or US, could you try one of those?  I might be completely wrong, but it seems to be a factor in Issue #5

**Comment by tdejneka** [comment]
> Which country are you logging in to? 
US

**Comment by tdejneka** [comment]
From the lack of replies, I now understand what you meant by "not a true fork". This repo only serves as a means of distributing updated libraries for `node-red-contrib-alexa-remote2` and nothing more.

Neither repo's product works for me so I'll have to look for an alternative.
